#NOT member of Org and signed up TCI and has read access and opens PR via fork
os: linux

language: java
services:
  - docker
cache: bundler
dist: focal

install: skip

jobs:
  include:
    - name: testing
      script: true

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT
after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
